---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/links":
    get:
      summary: list links
      tags:
      - Links
      security:
      - bearerAuth: []
      responses:
        '200':
          description: listed links
        '401':
          description: unauthorized user
    post:
      summary: create link
      tags:
      - Links
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: link registered
        '400':
          description: bad request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                link:
                  type: object
                  properties:
                    url:
                      type: string
                      default: www.google.com.mx
              required:
              - url
  "/links/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    put:
      summary: update link
      tags:
      - Links
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: link registered
        '400':
          description: bad request
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                link:
                  type: object
                  properties:
                    url:
                      type: string
                      default: www.google.com.mx
              required:
              - url
    delete:
      summary: delete link
      tags:
      - Links
      security:
      - bearerAuth: []
      responses:
        '200':
          description: link deleted
        '404':
          description: not found
  "/registration":
    post:
      summary: new registration
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: user registered
        '400':
          description: bad request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      default: default@email.com
                    password:
                      type: string
                      default: '12345678'
              required:
              - email
              - password
  "/sign_in":
    post:
      summary: log in
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: user logged
        '400':
          description: bad request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      default: default@email.com
                    password:
                      type: string
                      default: '12345678'
              required:
              - email
              - password
servers:
- url: http://localhost:3000
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
